### ISSUE TITLE
rollup 3 support

### ISSUE THREAD

**Issue by ryzokuken** [GoogleChromeLabs/rollup-plugin-webbundle#24]
The current `peerDependencies` require `rollup < 3.0.0` does the plugin not yet work with rollup 3?

**Comment by sonkkeli** [comment]
It was there probably just for precautiousness. Tested with v3.17.3 and that worked so upgraded the limit now to v4.0.0.

[Update the Rollup version restriction from v3.0.0 to v4.0.0](https://github.com/GoogleChromeLabs/rollup-plugin-webbundle/pull/25)

**Comment by ryzokuken** [comment]
@sonkkeli thanks a lot!

**Comment by sonkkeli** [comment]
It's still not available in the published npm version yet though, but will be in the near future :)

**Comment by ryzokuken** [comment]
Sure, I'll wait for the release or use the version from GitHub if that's okay.
